import React from "react";
import Image from "next/image";
import type { Metadata } from "next";

import Logo from "@/components/Logo";
import ThemeSwitcher from "@/components/ThemeSwitcher";

export const metadata: Metadata = {
  title: "Form Builder Dashboard- KitAN",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex flex-col max-h-screen min-w-full min-h-screen bg-backgrond">
      <nav className="flex justify-between items-center border-b border-border h-[60px] px-4 py-2">
        <Logo />
        <div className="flex items-center gap-4">
          <ThemeSwitcher />
        </div>
      </nav>
      <main className="flex items-center justify-center flex-grow w-full h-full">
        {children}
      </main>
    </div>
  );
}
