import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Form Builder - KitAN",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <div className="flex flex-grow w-full mx-auto">{children}</div>;
}
